import { ICartItemForm } from "./interface";

export const MockCartItem: ICartItemForm = {
  quantity: 7,
  price: 12500,
  item: [
    {
      quantity: 1,
      totalPrice: 3400,
      itemDetail: {
        itemCode: "T01",
        itemDesc: "Los Angeles Lakers Icon Edition 2022/23",
        itemSubDesc: "เสื้อแข่งผู้ชาย Nike Dri-FIT NBA Swingman",
        itemType: "cloth",
        itemSubType: "top",
        sizing: true,
        price: 3400,
        status: "stock",
        size: "M (44)",
        watchList: true,
        imgSource: "/images/01.png",
      },
    },
    {
      quantity: 1,
      totalPrice: 4300,
      itemDetail: {
        itemCode: "JD01",
        itemDesc: "Air Jordan 1 Low",
        itemSubDesc: "รองเท้าผู้ชาย",
        itemType: "sneaker",
        itemSubType: "wearing_sneaker",
        sizing: true,
        price: 4300,
        status: "stock",
        size: "10",
        watchList: false,
        imgSource: "/images/02.png",
      },
    },
    {
      quantity: 3,
      totalPrice: 3600,
      itemDetail: {
        itemCode: "PT01",
        itemDesc: "Nike Dri-FIT Challenger",
        itemSubDesc: "กางเกงขาสั้นอเนกประสงค์มีซับใน 5 นิ้วผู้ชาย",
        itemType: "cloth",
        itemSubType: "upper",
        sizing: true,
        price: 1200,
        status: "stock",
        size: "L",
        watchList: false,
        imgSource: "/images/03.png",
      },
    },
    {
      quantity: 2,
      totalPrice: 1200,
      itemDetail: {
        itemCode: "JD02",
        itemDesc: "Nike Everyday Plus Cushioned",
        itemSubDesc: "ถุงเท้าเทรนนิ่งข้อยาว (3 คู่)",
        itemType: "wearing",
        itemSubType: "sock",
        sizing: true,
        price: 600,
        status: "stock",
        size: "M(5Y-7Y/W6-10/M6-8)",
        watchList: false,
        imgSource: "/images/04.png",
      },
    },
  ],
  coupon: [
    {
      couponCode: "FA6886857871",
      couponDesc: "500 OFF",
      couponSubDesc: "Payday",
      warningDesc: "valid until 31 Dec 2026",
      couponType: "coupon",
      discount: 500,
      discountType: "amount",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "FA4768903526",
      couponDesc: "15,000 OFF",
      couponSubDesc: "Special Gift Coupon",
      warningDesc: "valid until 31 Dec 2029",
      couponType: "coupon",
      discount: 15000,
      discountSubtracting: undefined,
      discountType: "amount",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "FA688685787A",
      couponDesc: "25% OFF",
      couponSubDesc: "Payday",
      warningDesc: "valid until 31 Dec 2026",
      couponType: "coupon",
      discount: 25,
      discountType: "percent",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "FA476890352A",
      couponDesc: "15,000 OFF",
      couponSubDesc: "Special Gift Coupon",
      warningDesc: "valid until 31 Dec 2029",
      couponType: "coupon",
      discount: 15000,
      discountSubtracting: undefined,
      discountType: "amount",
      isSelected: false,
      status: "expire",
    },
  ],
  ontop: [
    {
      couponCode: "OT4563918988",
      couponDesc: "10% OFF",
      couponSubDesc: "Only Sneakers",
      warningDesc: "valid until 31 Dec 2029",
      couponType: "ontop",
      discount: 10,
      discountSubtracting: undefined,
      discountType: "percent",
      fixCategory: "sneaker",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "OT4544418988",
      couponDesc: "5% OFF",
      couponSubDesc: "Only Sneakers",
      warningDesc: "valid until 31 Dec 2029",
      couponType: "ontop",
      discount: 5,
      discountSubtracting: undefined,
      discountType: "percent",
      fixCategory: "sneaker",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "OT4987111988",
      couponDesc: "10% OFF",
      couponSubDesc: "Only Cloth",
      warningDesc: "-",
      couponType: "ontop",
      discount: 10,
      discountSubtracting: undefined,
      discountType: "percent",
      fixCategory: "cloth",
      isSelected: false,
      status: "available",
    },
  ],
  seasonal: [
    {
      couponCode: "SS4987111000",
      couponDesc: "50 OFF Every 1000฿",
      couponSubDesc: "Black Friday",
      warningDesc: "-",
      couponType: "seasonal",
      discount: 50,
      discountSubtracting: 1000,
      discountType: "subtracting",
      fixCategory: "sneaker",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "SS5456743990",
      couponDesc: "75 OFF Every 1000฿",
      couponSubDesc: "Black Friday",
      warningDesc: "this coupon is out",
      couponType: "seasonal",
      discount: 75,
      discountSubtracting: 1000,
      discountType: "subtracting",
      fixCategory: "sneaker",
      isSelected: false,
      status: "available",
    },
    {
      couponCode: "SS5457778990",
      couponDesc: "100 OFF Every 1000฿",
      couponSubDesc: "Black Friday",
      warningDesc: "this coupon is out",
      couponType: "seasonal",
      discount: 50,
      discountSubtracting: 1000,
      discountType: "subtracting",
      fixCategory: "sneaker",
      isSelected: false,
      status: "expire",
    },
  ],
  selectDiscount: {
    point: 0,
  },
  point: {
    customerPoint: 2799,
    percentAvailable: 20,
    isSelectpoint: false,
  },
};
